import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trabalho LPE",
  description: "Generated by create next app",
};

/*************  ✨ Windsurf Command ⭐  *************/
/**
 * The root layout of the application.
 *
 * This component is responsible for rendering the HTML element, as well as
 * the `<body>` element and its children.
 *
 * It also sets up the font styles for the entire application.
 *
 * @param children - The children of the layout, which should include the
 *                    application's routes.
 * @returns The root layout of the application.
 */
/*******  b414b067-99f8-4228-9f69-aba13b210056  *******/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
